version: '3.4'
services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  deltanotifier:
    restart: "no"
  database:
    environment:
      LOG_INCOMING_SPARQL_QUERIES: "true"
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  file:
    restart: "no"
  download-url:
    restart: "no"
  automatic-submission:
    restart: "no"
  import-submission:
    restart: "no"
  validate-submission:
    restart: "no"
  verify-submission:
    restart: "no"
  toezicht-flattened-form-data-generator:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:0.3.1
