services:
  frontend:
    restart: "no"
  dashboard:
    restart: "no"
  frontend-worship-decisions:
    restart: "no"
  identifier:
    restart: "no"
  dispatcher:
    restart: "no"
  deltanotifier:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  file:
    restart: "no"
  search-query-management:
    restart: "no"
  download-url:
    restart: "no"
  automatic-submission:
    restart: "no"
  import-submission:
    restart: "no"
  enrich-submission:
    restart: "no"
  validate-submission:
    restart: "no"
  verify-submission:
    restart: "no"
  toezicht-flattened-form-data-generator:
    restart: "no"
  person-uri-for-social-security-number:
    restart: "no"
  clean-up-submission:
    restart: "no"
  mocklogin:
    restart: "no"
  update-bestuurseenheid-mock-login:
    restart: "no"
  yasgui:
    image: redpencil/yasgui:latest
    restart: "no"
    environment:
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
  job-controller:
    restart: "no"
  op-public-consumer:
    restart: "no"
  vendor-login:
    restart: "no"
  sparql-authorization-wrapper:
    restart: "no"
  vendor-data-distribution:
    restart: "no"
    environment:
      HOSTNAME: "http://databankerediensten.localhost/"
  worship-decisions-cross-reference:
    environment:
      WORSHIP_DECISIONS_BASE_URL: "http://databankerediensten.localhost/search/submissions/"
    restart: "no"
  worship-submissions-graph-dispatcher:
    restart: "no"
  project-scripts:
    restart: "no"
