version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: lblod/frontend-meldingsplichtige-api:0.11.0
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dashboard:
    image: lblod/frontend-dashboard:1.5.2
    environment:
      EMBER_LOGIN_ROUTE: 'mock-login'
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.6
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/:/opt/virtuoso-scripts
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    environment:
      MU_SPARQL_TIMEOUT: '300'
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  cache:
   image: semtech/mu-cache:2.0.2
   links:
     - resource:backend
   labels:
     - "logging=true"
   restart: always
   logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.21.1
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: cecemel/file-service:3.3.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
    links:
      - database:database
  download-url:
    image: lblod/download-url-service:1.0.0
    environment:
      CACHING_MAX_RETRIES: "3"
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  automatic-submission:
    image: lblod/automatic-submission-service:1.0.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  import-submission:
    image: lblod/import-submission-service:1.0.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  enrich-submission:
    image: lblod/enrich-submission-service:1.1.0
    environment:
      ACTIVE_FORM_FILE: "share://semantic-forms/20221103143904-forms.ttl"
    volumes:
      - ./config/semantic-forms:/share/semantic-forms
      - ./data/files/submissions:/share/submissions
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  validate-submission:
    image: lblod/validate-submission-service:1.0.0
    environment:
      MAX_BODY_SIZE: "10000kb"
    volumes:
      - ./config/semantic-forms:/share/semantic-forms
      - ./data/files/submissions:/share/submissions
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  verify-submission:
    image: lblod/verify-submission-service:0.1.0
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  toezicht-flattened-form-data-generator:
    image: lblod/toezicht-flattened-form-data-generator:1.0.1
    volumes:
      - ./data/files/submissions:/share/submissions
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  person-uri-for-social-security-number:
    image: lblod/person-uri-for-social-security-number-service:0.4.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  clean-up-submission:
    image:  lblod/clean-up-submission-service:0.3.2
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  mocklogin:
    image: lblod/mock-login-service:0.4.0
  job-controller:
    image: lblod/job-controller-service:1.0.0
    volumes:
      - ./config/job-controller/config.json:/config/config.json
    labels:
      - "logging=true"
    restart: "always"
    logging: *default-logging

##############################################################################
# Vendor endpoint
##############################################################################

  vendor-login:
    image: lblod/vendor-login-service:1.0.0
  sparql-authorization-wrapper:
    image: lblod/sparql-authorization-wrapper-service:1.0.0
    volumes:
      - ./config/sparql-authorization-wrapper:/config
  vendor-data-distribution:
    image: lblod/vendor-data-distribution-service:1.0.0
