version: '3.4'
services:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.3.1
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  migrations:
    restart: "no"
  resource:
    restart: "no"
  file:
    restart: "no"
