(define-resource file ()
  :class (s-prefix "nfo:FileDataObject")
  :properties `((:filename :string ,(s-prefix "nfo:fileName"))
                (:format :string ,(s-prefix "dct:format"))
                (:size :number ,(s-prefix "nfo:fileSize"))
                (:extension :string ,(s-prefix "dbpedia:fileExtension"))
                (:created :datetime ,(s-prefix "nfo:fileCreated")))
  :has-one `((file :via ,(s-prefix "nie:dataSource")
                   :inverse t
                   :as "download"))
  :resource-base (s-url "http://data.lblod.info/files/")
  :features `(include-uri)
  :on-path "files")

  (define-resource file-download-status ()
    :class (s-prefix "lblodDataGift:FileDownloadStatus") ;;Subclass of skos:Concept
    :properties `((:label :string ,(s-prefix "skos:prefLabel")))
    :resource-base (s-url "http://lblod.data.gift/file-download-statuses/")
    :features `(include-uri)
    :on-path "file-download-states")