(define-resource gebruiker ()
  :class (s-prefix "foaf:Person")
  :properties `((:voornaam             :string ,(s-prefix "foaf:firstName"))
                (:achternaam           :string ,(s-prefix "foaf:familyName"))
                (:rijksregister-nummer :string ,(s-prefix "dct:identifier")))
  :has-many `((account :via ,(s-prefix "foaf:account")
                       :as "accounts")
              (bestuurseenheid :via ,(s-prefix "foaf:member")
                               :as "bestuurseenheden"))
  :resource-base (s-url "http://data.lblod.info/id/gebruiker/")
  :on-path "gebruikers")

(define-resource account ()
  :class (s-prefix "foaf:OnlineAccount")
  :properties `((:provider :via ,(s-prefix "foaf:accountServiceHomepage"))
                (:vo-id :via ,(s-prefix "dct:identifier")))
  :has-one `((gebruiker :via ,(s-prefix "foaf:account")
                        :inverse t
                        :as "gebruiker"))
  :resource-base (s-url "http://data.lblod.info/id/account/")
  :on-path "accounts")
