(in-package :mu-cl-resources)

(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "besluit" "http://data.vlaanderen.be/ns/besluit#")
(add-prefix "mandaat" "http://data.vlaanderen.be/ns/mandaat#")
(add-prefix "eli" "http://data.europa.eu/eli/ontology#")
(add-prefix "adms" "http://www.w3.org/ns/adms#")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "pav" "http://purl.org/pav/")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "schema" "http://schema.org/")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")
(add-prefix "meb" "http://rdf.myexperiment.org/ontologies/base/")
(add-prefix "melding" "http://lblod.data.gift/vocabularies/automatische-melding/")
(add-prefix "lblodBesluit" "http://lblod.data.gift/vocabularies/besluit/")
(add-prefix "muAccount" "http://mu.semte.ch/vocabularies/account/")
(add-prefix "elod" "http://linkedeconomy.org/ontology#")
(add-prefix "rdfs" "https://www.w3.org/2000/01/rdf-schema#")
(add-prefix "org" "http://www.w3.org/ns/org#")
