(define-resource inzending ()
  :class (s-prefix "meb:Submission")
  :properties `((:url :url ,(s-prefix "prov:atLocation"))
                (:beschrijving :string ,(s-prefix "dct:description"))
                (:opmerking :string ,(s-prefix "rdfs:comment")))
  :has-one `((bestuurseenheid :via ,(s-prefix "pav:createdBy")
                           :as "organization")
             (vendor :via ,(s-prefix "foaf:Agent")
                        :as "publisher")
             (inzending-document :via ,(s-prefix "dct:subject")
                                 :as "submitted-resource")
             (inzending-status :via ,(s-prefix "adms:status")
                     :as "status")
             (authenticity-type :via ,(s-prefix "melding:authenticityType")
                               :as "authenticity-type"))
  :has-many `((file :via ,(s-prefix "nfo:FileDataObject")
                    :as "file"))
  :resource-base (s-url "http://data.lblod.info/inzendingen/")
  :features `(include-uri)
  :on-path "inzendingen")

(define-resource vendor ()
  :class (s-prefix "ext:Vendor") ; Subclass of foaf:Agent
  :properties `((:name :string ,(s-prefix "foaf:name"))
                (:key :string ,(s-prefix "muAccount:key")))
  :resource-base (s-url "http://data.lblod.info/vendors/")
  :features `(include-uri)
  :on-path "vendors")

(define-resource inzending-document ()
  :class (s-prefix "ext:InzendingDocument") ; Subclass of foaf:Document
  :properties `((:publicationDate :date ,(s-prefix "eli:date_publication"))
                (:reportYear :gYear ,(s-prefix "elod:financialYear"))
                (:firstDateInForce :date ,(s-prefix "eli:first_date_entry_in_force"))
                (:dateNoLongerInForce :date ,(s-prefix "eli:date_no_longer_in_force"))
                (:hasAdditionalTaxRate :boolean ,(s-prefix "lblodBesluit:hasAdditionalTaxRate")))
  :has-one `((bestuursorgaan :via ,(s-prefix "eli:passed_by")
                             :as "passed-by")
             (bestuurseenheid :via ,(s-prefix "eli:is_about")
                              :as "subject")
             (chart-of-account :via ,(s-prefix "lblodBesluit:chartOfAccount")
                               :as "chart-of-account")
             (aanslagvoet :via ,(s-prefix "lblodBesluit:taxRate")
                       :as "tax-rate")
             (tax-type :via ,(s-prefix "lblodBesluit:taxType")
                       :as "tax-type"))
  :resource-base (s-url "http://data.lblod.info/inzending-documenten/")
  :features `(include-uri)
  :on-path "inzending-documenten")

(define-resource aanslagvoet ()
  :class (s-prefix "lblodBesluit:TaxRate") ; Subclass of schema:UnitPriceSpecification
  :properties `((:amount :number ,(s-prefix "schema:price"))
                (:unit :string ,(s-prefix "schema:unitText"))
                (:base :string ,(s-prefix "lblodBesluit:taxableBase"))
                (:description :string ,(s-prefix "schema:description")))
  :resource-base (s-url "http://data.lblod.info/aanslagvoeten/")
  :features `(include-uri)
  :on-path "aanslagvoeten")
