PREFIX adres: <https://data.vlaanderen.be/ns/adres#>
PREFIX locn: <http://www.w3.org/ns/locn#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?adres adres:adresIsGelegenIn ?provincie.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/landing-zone/op-public> {
    ?adres a locn:Address;
      adres:adresIsGelegenIn ?provincie.
  }
}
